In [12]:
import pandas as pd
import numpy as np

df = pd.read_csv("h08.csv",header=[0,1])

print(df)

df.to_csv("h08(2).csv",index=True)

                 State          2021 Unnamed: 2_level_0     2020 (41)  \
    Unnamed: 0_level_1 Median income     Standard error Median income
0        United States        70,784                368        68,010
1              Alabama        56,929              2,294        54,689
2               Alaska        81,133              3,967        74,746
3              Arizona        70,821              3,394        67,088
4             Arkansas        50,784              1,440        50,777
..                 ...           ...                ...           ...
102           Virginia        80,268              2,953        86,053
103         Washington        87,648              3,307        85,157
104      West Virginia        46,836              2,247        54,396
105          Wisconsin        69,943              3,133        70,553
106            Wyoming        71,052              3,919        68,506

    Unnamed: 4_level_0          2019 Unnamed: 6_level_0          2018  \
        Standard error Median income     Standard error Median income
0                  535        68,703                550        63,179
1                2,563        56,200              2,512        49,936
2                3,557        78,394              6,685        68,734
3                3,409        70,674              3,391        62,283
4                1,837        54,539              2,384        49,781
..                 ...           ...                ...           ...
102              3,261        86,172              3,239        83,243
103              3,242        87,381              3,094        86,021
104              2,280        56,916              3,174        54,566
105              5,051        71,380              2,462        67,574
106              2,309        69,027              3,998        67,477

    Unnamed: 8_level_0     2017 (40)  ...          1988 Unnamed: 72_level_0  \
        Standard error Median income  ... Median income      Standard error
0                  420        61,136  ...        27,225                 139
1                2,423        50,865  ...        19,948                 912
2                3,390        77,987  ...        33,103               1,183
3                2,291        59,700  ...        26,435                 843
4                2,108        49,751  ...        20,172                 706
..                 ...           ...  ...           ...                 ...
102              3,330        78,265  ...        72,089               2,912
103              3,264        79,071  ...        71,381               2,274
104              1,443        51,900  ...        42,733               2,054
105              2,200        70,164  ...        65,304               2,160
106              4,199        65,803  ...        58,335               2,418

        1987 (21) Unnamed: 74_level_0          1986 Unnamed: 76_level_0  \
    Median income      Standard error Median income      Standard error
0          26,061                 127        24,897                 129
1          19,734               1,147        19,132                 885
2          33,233               1,497        31,356               1,017
3          26,749                 892        25,500                 718
4          18,827               1,008        18,730                 765
..            ...                 ...           ...                 ...
102        68,626               2,318        70,322               2,542
103        62,502               2,535        63,615               2,248
104        39,367               1,780        38,963               2,142
105        60,328               3,226        62,548               1,900
106        63,122               3,336        55,754               2,042

        1985 (20) Unnamed: 78_level_0     1984 (19) Unnamed: 80_level_0
    Median income      Standard error Median income      Standard error
0          23,618                 128        22,415                 102
1          18,333                 760        17,310                 605
2          34,782               1,089        32,356               1,473
3          23,877                 744        21,425                 609
4          17,451                 764        15,674                 748
..            ...                 ...           ...                 ...
102        68,456               3,188        66,064               2,177
103        57,791               1,820        62,308               2,050
104        38,487               1,994        41,950               1,514
105        55,976               2,796        51,663               2,045
106        53,170               2,526        59,317               1,821

[107 rows x 81 columns]